# Generated by Django 5.2.4 on 2025-08-03 06:06

from django.db import migrations

INITIAL_DIRECTIONS = [
    {"name": "Đông", "element": "Mộc"},
    {"name": "Tây", "element": "Kim"},
    {"name": "Nam", "element": "Hỏa"},
    {"name": "Bắc", "element": "Thủy"},
    {"name": "Đông Bắc", "element": "Thổ"},
    {"name": "Tây Nam", "element": "Thổ"},
    {"name": "Đông Nam", "element": "Mộc"},
    {"name": "Tây Bắc", "element": "Kim"},
]

def add_directions(apps, schema_editor):
    """Hàm để thêm dữ liệu vào bảng Direction."""
    Direction = apps.get_model('landifys', 'Direction')
    for d in INITIAL_DIRECTIONS:
        Direction.objects.create(name=d['name'], element=d['element'])

def remove_directions(apps, schema_editor):
    """Hàm để xóa dữ liệu khi rollback migration (tùy chọn)."""
    Direction = apps.get_model('landifys', 'Direction')
    Direction.objects.filter(name__in=[d['name'] for d in INITIAL_DIRECTIONS]).delete()

class Migration(migrations.Migration):
    dependencies = [
        ('landifys', '0003_direction_element_alter_direction_name'),
    ]

    operations = [
        migrations.RunPython(add_directions, reverse_code=remove_directions),
    ]
