# Generated by Django 5.2.4 on 2025-08-03 10:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landifys', '0002_add_initial_directions'),
    ]

    operations = [
        migrations.CreateModel(
            name='Protest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('reason', models.TextField()),
                ('resolution_note', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('IN_PROGRESS', 'Đang xem xét'), ('RESOLVED', 'Đã giải quyết'), ('REJECTED', 'Từ chối')], default='IN_PROGRESS', max_length=20)),
                ('admin', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='handled_protests', to=settings.AUTH_USER_MODEL)),
                ('listing', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='landifys.listing')),
                ('protester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='protests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-id'],
                'abstract': False,
            },
        ),
    ]
