# Generated by Django 5.2.4 on 2025-08-03 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landifys', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='direction',
            name='element',
            field=models.CharField(default=1, help_text='Hành tương ứng, ví dụ: Mộc, Kim, Hỏa', max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='direction',
            name='name',
            field=models.CharField(help_text='Tên hướng, ví dụ: Đông, Tây Nam', max_length=50, unique=True),
        ),
    ]
