# Generated by Django 5.2.4 on 2025-09-03 18:07

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="BuySellDetail",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("active", models.BooleanField(default=True)),
                ("created_date", models.DateTimeField(auto_now_add=True)),
                ("updated_date", models.DateTimeField(auto_now=True)),
                ("is_mortgaged", models.BooleanField(blank=True, null=True, verbose_name="Đang thế chấp ngân hàng?")),
                (
                    "condition_status",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("NEW", "Mới 100%"),
                            ("RENOVATED", "Đã cải tạo"),
                            ("GOOD", "Tình trạng tốt"),
                            ("NEEDS_REPAIR", "Cần sửa chữa"),
                        ],
                        max_length=20,
                        null=True,
                        verbose_name="Tình trạng hiện tại",
                    ),
                ),
            ],
            options={
                "verbose_name": "Chi tiết tin Bán/Mua",
                "verbose_name_plural": "Các chi tiết tin Bán/Mua",
            },
        ),
        migrations.CreateModel(
            name="Listing",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("active", models.BooleanField(default=True)),
                ("created_date", models.DateTimeField(auto_now_add=True)),
                ("updated_date", models.DateTimeField(auto_now=True)),
                ("title", models.CharField(max_length=255, verbose_name="Tiêu đề")),
                ("content", ckeditor.fields.RichTextField(verbose_name="Nội dung")),
                (
                    "price_value",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=19, null=True, verbose_name="Giá trị (số)"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("AVAILABLE", "Đang đăng"),
                            ("PENDING", "Đang chờ giao dịch"),
                            ("COMPLETED", "Đã giao dịch"),
                            ("CANCELLED", "Đã hủy"),
                        ],
                        default="AVAILABLE",
                        max_length=20,
                        verbose_name="Trạng thái",
                    ),
                ),
                (
                    "spam_check_status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Chờ kiểm tra"),
                            ("CLEAN", "Trong sạch"),
                            ("FLAGGED", "Bị đánh dấu spam"),
                        ],
                        default="PENDING",
                        max_length=20,
                        verbose_name="Trạng thái Spam",
                    ),
                ),
                ("commission_percentage", models.FloatField(default=0.0, verbose_name="Phần trăm hoa hồng (%)")),
            ],
            options={
                "verbose_name": "Tin đăng",
                "verbose_name_plural": "Các Tin đăng",
            },
        ),
        migrations.CreateModel(
            name="ListingPropertyFeatureValue",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("active", models.BooleanField(default=True)),
                ("created_date", models.DateTimeField(auto_now_add=True)),
                ("updated_date", models.DateTimeField(auto_now=True)),
                ("value", models.JSONField(verbose_name="Giá trị")),
            ],
            options={
                "verbose_name": "Giá trị Đặc điểm của Tin đăng",
                "verbose_name_plural": "Các Giá trị Đặc điểm của Tin đăng",
            },
        ),
        migrations.CreateModel(
            name="ListingType",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("active", models.BooleanField(default=True)),
                ("created_date", models.DateTimeField(auto_now_add=True)),
                ("updated_date", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=50, unique=True)),
            ],
            options={
                "verbose_name": "Loại tin đăng",
                "verbose_name_plural": "Các Loại tin đăng",
            },
        ),
        migrations.CreateModel(
            name="ListingVip",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("active", models.BooleanField(default=True)),
                ("created_date", models.DateTimeField(auto_now_add=True)),
                ("updated_date", models.DateTimeField(auto_now=True)),
                ("duration_days", models.IntegerField(verbose_name="Số ngày VIP đã mua")),
            ],
            options={
                "verbose_name": "Trạng thái VIP của Tin đăng",
                "verbose_name_plural": "Các trạng thái VIP của Tin đăng",
                "ordering": ["-created_date"],
            },
        ),
        migrations.CreateModel(
            name="ProjectDetail",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("active", models.BooleanField(default=True)),
                ("created_date", models.DateTimeField(auto_now_add=True)),
                ("updated_date", models.DateTimeField(auto_now=True)),
                ("developer", models.CharField(max_length=255, verbose_name="Chủ đầu tư")),
                (
                    "total_area",
                    models.CharField(blank=True, max_length=50, null=True, verbose_name="Tổng diện tích đất dự án"),
                ),
                ("building_density", models.FloatField(blank=True, null=True, verbose_name="Mật độ xây dựng (%)")),
                ("scale_description", models.TextField(blank=True, null=True, verbose_name="Mô tả quy mô")),
                ("total_units", models.PositiveIntegerField(blank=True, null=True, verbose_name="Tổng số căn")),
                (
                    "unit_area_range",
                    models.CharField(blank=True, max_length=100, null=True, verbose_name="Khoảng diện tích sản phẩm"),
                ),
                (
                    "ownership_form",
                    models.CharField(blank=True, max_length=255, null=True, verbose_name="Hình thức sở hữu"),
                ),
                ("launch_date", models.DateField(blank=True, null=True, verbose_name="Ngày mở bán")),
                ("handover_date", models.DateField(blank=True, null=True, verbose_name="Ngày bàn giao (dự kiến)")),
            ],
            options={
                "verbose_name": "Chi tiết tin Dự án",
                "verbose_name_plural": "Các chi tiết tin Dự án",
            },
        ),
        migrations.CreateModel(
            name="RentalDetail",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("active", models.BooleanField(default=True)),
                ("created_date", models.DateTimeField(auto_now_add=True)),
                ("updated_date", models.DateTimeField(auto_now=True)),
                (
                    "deposit_amount",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=19, null=True, verbose_name="Số tiền cọc"
                    ),
                ),
                (
                    "min_lease_duration",
                    models.PositiveIntegerField(blank=True, null=True, verbose_name="Thời hạn thuê tối thiểu (tháng)"),
                ),
                ("allow_pets", models.BooleanField(blank=True, null=True, verbose_name="Cho phép nuôi thú cưng")),
                ("allow_smoking", models.BooleanField(blank=True, null=True, verbose_name="Cho phép hút thuốc")),
                (
                    "max_occupants",
                    models.PositiveIntegerField(blank=True, null=True, verbose_name="Số người ở tối đa"),
                ),
                (
                    "is_electricity_included",
                    models.BooleanField(default=False, verbose_name="Giá thuê đã bao gồm điện"),
                ),
                ("is_water_included", models.BooleanField(default=False, verbose_name="Giá thuê đã bao gồm nước")),
                (
                    "is_internet_included",
                    models.BooleanField(default=False, verbose_name="Giá thuê đã bao gồm Internet/Truyền hình cáp"),
                ),
                (
                    "is_management_fee_included",
                    models.BooleanField(default=False, verbose_name="Giá thuê đã bao gồm phí quản lý"),
                ),
                ("available_from_date", models.DateField(blank=True, null=True, verbose_name="Ngày có thể dọn vào")),
            ],
            options={
                "verbose_name": "Chi tiết tin Cho thuê",
                "verbose_name_plural": "Các chi tiết tin Cho thuê",
            },
        ),
        migrations.CreateModel(
            name="UnitPrice",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=50, unique=True, verbose_name="Tên đơn vị")),
                ("code", models.CharField(max_length=50, unique=True, verbose_name="Mã đơn vị")),
                ("is_per_area_unit", models.BooleanField(default=False, verbose_name="Là đơn vị theo diện tích")),
            ],
            options={
                "verbose_name": "Đơn vị giá",
                "verbose_name_plural": "Các Đơn vị giá",
            },
        ),
        migrations.CreateModel(
            name="VipType",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("active", models.BooleanField(default=True)),
                ("created_date", models.DateTimeField(auto_now_add=True)),
                ("updated_date", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=100, unique=True, verbose_name="Tên gói VIP")),
                ("code", models.CharField(max_length=50, unique=True, verbose_name="Mã code (cho Frontend)")),
                (
                    "price_per_day",
                    models.DecimalField(decimal_places=2, max_digits=10, verbose_name="Giá mỗi ngày (VND)"),
                ),
                ("sort_priority", models.IntegerField(default=0, verbose_name="Độ ưu tiên sắp xếp")),
                ("boost_multiplier", models.IntegerField(default=1, verbose_name="Hệ số nhân (ví dụ: 30 cho X30)")),
                ("allow_auto_top_up", models.BooleanField(default=False, verbose_name="Cho phép tự động đẩy tin")),
            ],
            options={
                "verbose_name": "Loại tin VIP",
                "verbose_name_plural": "Các loại tin VIP",
                "ordering": ["-sort_priority"],
            },
        ),
    ]
