# Generated by Django 5.2.4 on 2025-09-03 18:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("listings", "0002_initial"),
        ("properties", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="listing",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="listings",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Người đăng tin",
            ),
        ),
        migrations.AddField(
            model_name="buyselldetail",
            name="listing",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="buysell_detail",
                to="listings.listing",
                verbose_name="Tin đăng",
            ),
        ),
        migrations.AddField(
            model_name="listingpropertyfeaturevalue",
            name="feature",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="listing_values",
                to="properties.propertyfeature",
            ),
        ),
        migrations.AddField(
            model_name="listingpropertyfeaturevalue",
            name="listing",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, related_name="feature_values", to="listings.listing"
            ),
        ),
        migrations.AddField(
            model_name="listing",
            name="features",
            field=models.ManyToManyField(
                related_name="listings",
                through="listings.ListingPropertyFeatureValue",
                to="properties.propertyfeature",
                verbose_name="Các đặc điểm chi tiết",
            ),
        ),
        migrations.AddField(
            model_name="listing",
            name="listing_type",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="listings.listingtype",
                verbose_name="Loại tin đăng (Bán/Thuê/Dự án)",
            ),
        ),
        migrations.AddField(
            model_name="listingvip",
            name="listing",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="vip_status",
                to="listings.listing",
                verbose_name="Tin đăng",
            ),
        ),
        migrations.AddField(
            model_name="projectdetail",
            name="listing",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="project_detail",
                to="listings.listing",
                verbose_name="Tin đăng",
            ),
        ),
        migrations.AddField(
            model_name="projectdetail",
            name="product_types",
            field=models.ManyToManyField(
                blank=True, to="properties.propertytype", verbose_name="Các loại hình sản phẩm trong dự án"
            ),
        ),
        migrations.AddField(
            model_name="rentaldetail",
            name="listing",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="rental_detail",
                to="listings.listing",
                verbose_name="Tin đăng",
            ),
        ),
        migrations.AddField(
            model_name="listing",
            name="unit_price",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="listings.unitprice",
                verbose_name="Đơn vị giá",
            ),
        ),
        migrations.AddField(
            model_name="listingvip",
            name="vip_type",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="listings.viptype", verbose_name="Loại gói VIP"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="listingpropertyfeaturevalue",
            unique_together={("listing", "feature")},
        ),
    ]
