# Generated by Django 5.2.4 on 2025-09-05 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("listings", "0003_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="listingtype",
            name="code",
            field=models.CharField(
                default=50,
                help_text="Mã định danh không đổi, ví dụ: BUY_SELL, RENT, PROJECT",
                max_length=50,
                unique=True,
            ),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name="Promotion",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("active", models.BooleanField(default=True)),
                ("created_date", models.DateTimeField(auto_now_add=True)),
                ("updated_date", models.DateTimeField(auto_now=True)),
                ("code", models.CharField(max_length=50, unique=True, verbose_name="Mã khuyến mãi")),
                ("title", models.CharField(max_length=255, verbose_name="Tiêu đề (hiển thị cho user)")),
                ("description", models.TextField(verbose_name="Mô tả chi tiết")),
                (
                    "promo_type",
                    models.CharField(
                        choices=[("FREE_LISTING", "Miễn phí Tin đăng"), ("DISCOUNT_VIP", "Giảm giá Gói VIP")],
                        max_length=20,
                        verbose_name="Loại khuyến mãi",
                    ),
                ),
                (
                    "free_listing_days",
                    models.PositiveIntegerField(blank=True, null=True, verbose_name="Số ngày miễn phí (nếu có)"),
                ),
                (
                    "discount_percentage",
                    models.FloatField(blank=True, null=True, verbose_name="Phần trăm giảm giá (ví dụ: 20 cho 20%)"),
                ),
                ("start_date", models.DateTimeField(verbose_name="Ngày bắt đầu")),
                ("end_date", models.DateTimeField(verbose_name="Ngày kết thúc")),
                (
                    "applicable_vip_types",
                    models.ManyToManyField(blank=True, to="listings.viptype", verbose_name="Áp dụng cho các gói VIP"),
                ),
            ],
            options={
                "verbose_name": "Khuyến mãi",
                "verbose_name_plural": "Các Khuyến mãi",
                "ordering": ["-end_date"],
            },
        ),
    ]
