# Generated by Django 5.2.4 on 2025-09-07 20:05
#python manage.py migrate listings 0004

from django.db import migrations
from django.utils import timezone
from datetime import timedelta

MODEL_NAMES = ["UnitPrice", "ListingType", "VipType", "Promotion"]


def populate_initial_data(apps, schema_editor):
    """
    Hàm này sẽ xóa dữ liệu cũ và tạo dữ liệu mới.
    """
    # Lấy các model từ phiên bản lịch sử của app
    UnitPrice = apps.get_model('listings', 'UnitPrice')
    ListingType = apps.get_model('listings', 'ListingType')
    VipType = apps.get_model('listings', 'VipType')
    Promotion = apps.get_model('listings', 'Promotion')

    for model_name in MODEL_NAMES:
        Model = apps.get_model('listings', model_name)
        Model.objects.all().delete()
        print(f"\nDeleted all existing records from {model_name}.")
    # ----------------------------------------------------------------

    UnitPrice.objects.bulk_create([
        UnitPrice(name="VND", code="VND", is_per_area_unit=False),
        UnitPrice(name="/m²", code="PER_M2", is_per_area_unit=True),
        UnitPrice(name="/tháng", code="PER_MONTH", is_per_area_unit=False),
    ])
    print("Created UnitPrice records.")

    # --- Tạo dữ liệu mới cho ListingType ---
    ListingType.objects.bulk_create([
        ListingType(name="Mua Bán", code="BUY_SELL"),
        ListingType(name="Cho Thuê", code="RENT"),
        ListingType(name="Dự án", code="PROJECT"),
    ])
    print("Created ListingType records.")

    # --- Tạo dữ liệu mới cho VipType ---
    VipType.objects.bulk_create([
        VipType(name="VIP Kim Cương", code="VIP_DIAMOND", price_per_day=33000, sort_priority=100, boost_multiplier=30, allow_auto_top_up=True),
        VipType(name="VIP Vàng", code="VIP_GOLD", price_per_day=22000, sort_priority=50, boost_multiplier=15, allow_auto_top_up=True),
        VipType(name="VIP Bạc", code="VIP_SILVER", price_per_day=11000, sort_priority=20, boost_multiplier=5, allow_auto_top_up=False),
    ])
    print("Created VipType records.")

    # --- Tạo dữ liệu mới cho Promotion ---
    now = timezone.now()
    Promotion.objects.bulk_create([
        Promotion(
            code="KHACHMOI",
            title="Miễn phí 1 tin thường 15 ngày cho Khách hàng mới",
            description="Áp dụng cho tài khoản mới đăng ký trong vòng 7 ngày.",
            promo_type="FREE_LISTING",
            free_listing_days=15,
            start_date=now,
            end_date=now + timedelta(days=365)
        ),
        Promotion(
            code="VIPTHANG9",
            title="Giảm 20% gói tin VIP Vàng trong tháng 9",
            description="Áp dụng cho tất cả các tin đăng trong tháng 9.",
            promo_type="DISCOUNT_VIP",
            discount_percentage=20.0,
            start_date=now.replace(day=1, month=9),
            end_date=now.replace(day=30, month=9)
        )
    ])
    # Gán ManyToManyField sau khi đã tạo Promotion
    promo_vipthang9 = Promotion.objects.get(code="VIPTHANG9")
    vip_vang = VipType.objects.get(code="VIP_GOLD")
    promo_vipthang9.applicable_vip_types.add(vip_vang)
    print("Created Promotion records.")


def unpopulate_initial_data(apps, schema_editor):
    """
    Hàm này sẽ được gọi khi bạn rollback migration.
    Nó sẽ xóa tất cả dữ liệu đã được tạo.
    """
    for model_name in MODEL_NAMES:
        Model = apps.get_model('listings', model_name)
        Model.objects.all().delete()
        print(f"\nDeleted all records from {model_name} during rollback.")


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0004_listingtype_code_promotion'), # Phải phụ thuộc vào migration tạo bảng gần nhất
    ]

    operations = [
        migrations.RunPython(populate_initial_data, unpopulate_initial_data),
    ]
