# Generated by Django 5.2.4 on 2025-09-07 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("listings", "0005_initial_data"),
    ]

    operations = [
        migrations.AlterField(
            model_name="unitprice",
            name="code",
            field=models.CharField(max_length=50, unique=True, verbose_name="Mã đơn vị"),
        ),
    ]
