# Generated by Django 5.2.4 on 2025-09-09 22:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("listings", "0006_alter_unitprice_code"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="listingvip",
            options={
                "verbose_name": "Trạng thái VIP của Tin đăng",
                "verbose_name_plural": "Các trạng thái VIP của Tin đăng",
            },
        ),
        migrations.RemoveField(
            model_name="listingvip",
            name="duration_days",
        ),
        migrations.RemoveField(
            model_name="listingvip",
            name="id",
        ),
        migrations.AddField(
            model_name="listingvip",
            name="end_date",
            field=models.DateTimeField(blank=True, null=True, verbose_name="Ngày kết thúc VIP"),
        ),
        migrations.AlterField(
            model_name="listingvip",
            name="listing",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                primary_key=True,
                related_name="vip_status",
                serialize=False,
                to="listings.listing",
                verbose_name="Tin đăng",
            ),
        ),
        migrations.AlterField(
            model_name="listingvip",
            name="vip_type",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="listings.viptype",
                verbose_name="Loại gói VIP hiện tại",
            ),
        ),
        migrations.CreateModel(
            name="PromotionRule",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("active", models.BooleanField(default=True)),
                ("created_date", models.DateTimeField(auto_now_add=True)),
                ("updated_date", models.DateTimeField(auto_now=True)),
                ("title", models.CharField(max_length=255, verbose_name="Tên chương trình KM")),
                ("description", models.TextField(verbose_name="Mô tả chi tiết")),
                (
                    "promo_type",
                    models.CharField(
                        choices=[("FREE_LISTING", "Miễn phí Tin đăng"), ("DISCOUNT_VIP", "Giảm giá Gói VIP")],
                        max_length=20,
                        verbose_name="Loại khuyến mãi",
                    ),
                ),
                (
                    "free_listing_days",
                    models.PositiveIntegerField(blank=True, null=True, verbose_name="Số ngày đăng tin miễn phí"),
                ),
                (
                    "discount_percentage",
                    models.FloatField(blank=True, null=True, verbose_name="Phần trăm giảm giá VIP"),
                ),
                (
                    "trigger_event",
                    models.CharField(
                        choices=[("ON_SIGNUP", "Khi đăng ký tài khoản"), ("MANUAL", "Gán thủ công bởi admin")],
                        default="MANUAL",
                        max_length=20,
                        verbose_name="Sự kiện kích hoạt",
                    ),
                ),
                (
                    "validity_duration",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="Để trống nếu KM được gán thủ công với ngày hết hạn cụ thể.",
                        null=True,
                        verbose_name="Thời hạn hiệu lực (số ngày)",
                    ),
                ),
                (
                    "applicable_vip_types",
                    models.ManyToManyField(blank=True, to="listings.viptype", verbose_name="Áp dụng cho các gói VIP"),
                ),
            ],
            options={
                "verbose_name": "Quy tắc Khuyến mãi",
                "verbose_name_plural": "Các Quy tắc Khuyến mãi",
            },
        ),
        migrations.CreateModel(
            name="UserPromotion",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("active", models.BooleanField(default=True)),
                ("created_date", models.DateTimeField(auto_now_add=True)),
                ("updated_date", models.DateTimeField(auto_now=True)),
                ("code", models.CharField(max_length=50, unique=True, verbose_name="Mã khuyến mãi")),
                ("expiry_date", models.DateTimeField(verbose_name="Ngày hết hạn")),
                (
                    "status",
                    models.CharField(
                        choices=[("AVAILABLE", "Có thể sử dụng"), ("USED", "Đã sử dụng"), ("EXPIRED", "Đã hết hạn")],
                        default="AVAILABLE",
                        max_length=20,
                    ),
                ),
                ("used_at", models.DateTimeField(blank=True, null=True)),
                (
                    "rule",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="instances",
                        to="listings.promotionrule",
                    ),
                ),
                (
                    "used_on_listing",
                    models.ForeignKey(
                        blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to="listings.listing"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="user_promotions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Khuyến mãi của Người dùng",
                "verbose_name_plural": "Các Khuyến mãi của Người dùng",
                "ordering": ["-expiry_date"],
            },
        ),
        migrations.DeleteModel(
            name="Promotion",
        ),
    ]
