# Generated by Django 5.2.4 on 2025-09-16 19:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("listings", "0007_alter_listingvip_options_and_more"),
        ("properties", "0008_add_property_features_data"),
    ]

    operations = [
        migrations.CreateModel(
            name="ListingCategory",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("active", models.BooleanField(default=True)),
                ("created_date", models.DateTimeField(auto_now_add=True)),
                ("updated_date", models.DateTimeField(auto_now=True)),
                (
                    "listing_type",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="listings.listingtype"),
                ),
                (
                    "property_type",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="properties.propertytype"),
                ),
            ],
            options={
                "verbose_name": "Danh mục Hợp lệ",
                "verbose_name_plural": "Các Danh mục Hợp lệ",
                "ordering": ["listing_type__name", "property_type__name"],
                "unique_together": {("listing_type", "property_type")},
            },
        ),
    ]
