# Generated by Django 5.2.4 on 2025-09-16 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("listings", "0009_seed_listing_categories"),
        ("properties", "0008_add_property_features_data"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="projectdetail",
            name="listing",
        ),
        migrations.RemoveField(
            model_name="projectdetail",
            name="product_types",
        ),
        migrations.RemoveField(
            model_name="rentaldetail",
            name="listing",
        ),
        migrations.AlterModelOptions(
            name="listingcategory",
            options={
                "ordering": ["listing_type__name", "property_type__name"],
                "verbose_name": "Danh mục Đăng tin",
                "verbose_name_plural": "Các Danh mục Đăng tin",
            },
        ),
        migrations.AddField(
            model_name="listingcategory",
            name="applicable_features",
            field=models.ManyToManyField(
                blank=True, to="properties.propertyfeature", verbose_name="Các đặc điểm áp dụng"
            ),
        ),
        migrations.DeleteModel(
            name="BuySellDetail",
        ),
        migrations.DeleteModel(
            name="ProjectDetail",
        ),
        migrations.DeleteModel(
            name="RentalDetail",
        ),
    ]
