# Generated by Django 5.2.4 on 2025-09-16 23:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("listings", "0011_seed_listing_categories_with_features"),
    ]

    operations = [
        migrations.AddField(
            model_name="listing",
            name="scam_detector_version",
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name="Phiên bản AI phát hiện"),
        ),
        migrations.AddField(
            model_name="listing",
            name="scam_score",
            field=models.FloatField(blank=True, null=True, verbose_name="Điểm Scam (từ AI)"),
        ),
    ]
