# Generated by Django 5.2.4 on 2025-09-17 03:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("listings", "0012_listing_scam_detector_version_listing_scam_score"),
    ]

    operations = [
        migrations.AddField(
            model_name="listingcategory",
            name="applicable_unit_prices",
            field=models.ManyToManyField(blank=True, to="listings.unitprice", verbose_name="Các đơn vị giá áp dụng"),
        ),
        migrations.AddField(
            model_name="listingtype",
            name="applicable_unit_prices",
            field=models.ManyToManyField(blank=True, to="listings.unitprice", verbose_name="Các đơn vị giá áp dụng"),
        ),
    ]
