# Generated by Django 5.2.4 on 2025-09-17 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("listings", "0013_listingcategory_applicable_unit_prices_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="listing",
            name="price_value",
            field=models.DecimalField(
                blank=True, db_index=True, decimal_places=2, max_digits=19, null=True, verbose_name="Giá trị (số)"
            ),
        ),
    ]
