# Generated by Django 5.2.4 on 2025-09-19 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("listings", "0014_alter_listing_price_value"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="listingvip",
            options={
                "verbose_name": "Trạng thái VIP & Hóa đơn",
                "verbose_name_plural": "Các trạng thái VIP & Hóa đơn",
            },
        ),
        migrations.RemoveField(
            model_name="listingcategory",
            name="applicable_unit_prices",
        ),
        migrations.AddField(
            model_name="listingvip",
            name="amount",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=19, verbose_name="Số tiền thanh toán"),
        ),
        migrations.AddField(
            model_name="listingvip",
            name="pay_url",
            field=models.URLField(blank=True, max_length=512, null=True),
        ),
        migrations.AddField(
            model_name="listingvip",
            name="payment_code",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="listingvip",
            name="payment_method",
            field=models.CharField(
                blank=True, choices=[("MOMO", "Ví MoMo"), ("BANK", "Chuyển khoản")], max_length=50, null=True
            ),
        ),
        migrations.AddField(
            model_name="listingvip",
            name="payment_status",
            field=models.CharField(
                choices=[("PENDING", "Chờ thanh toán"), ("PAID", "Đã thanh toán"), ("FAILED", "Thanh toán thất bại")],
                default="PENDING",
                max_length=20,
            ),
        ),
    ]
