# Generated by Django 5.2.4 on 2025-09-19 07:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("listings", "0015_alter_listingvip_options_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="listing",
            name="listing_type",
        ),
        migrations.AddField(
            model_name="listing",
            name="listing_category",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="listings",
                to="listings.listingcategory",
                verbose_name="Danh mục tin đăng",
            ),
        ),
    ]
