# Generated by Django 5.2.4 on 2025-09-03 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Appointment",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("active", models.BooleanField(default=True)),
                ("created_date", models.DateTimeField(auto_now_add=True)),
                ("updated_date", models.DateTimeField(auto_now=True)),
                ("appointment_date", models.DateTimeField(verbose_name="Thời gian hẹn")),
                ("note", models.TextField(blank=True, null=True, verbose_name="Ghi chú")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Chờ xác nhận"),
                            ("CONFIRMED", "Đã xác nhận"),
                            ("COMPLETED", "Đã hoàn thành"),
                            ("CANCELLED", "Đã hủy"),
                        ],
                        default="PENDING",
                        max_length=20,
                        verbose_name="Trạng thái",
                    ),
                ),
            ],
            options={
                "verbose_name": "Lịch hẹn",
                "verbose_name_plural": "Các Lịch hẹn",
            },
        ),
        migrations.CreateModel(
            name="Review",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("active", models.BooleanField(default=True)),
                ("created_date", models.DateTimeField(auto_now_add=True)),
                ("updated_date", models.DateTimeField(auto_now=True)),
                (
                    "rating",
                    models.PositiveIntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], verbose_name="Điểm"),
                ),
                ("comment", models.TextField(verbose_name="Bình luận")),
            ],
            options={
                "verbose_name": "Đánh giá",
                "verbose_name_plural": "Các Đánh giá",
            },
        ),
        migrations.CreateModel(
            name="Wishlist",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("active", models.BooleanField(default=True)),
                ("created_date", models.DateTimeField(auto_now_add=True)),
                ("updated_date", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Danh sách yêu thích",
                "verbose_name_plural": "Các Danh sách yêu thích",
            },
        ),
    ]
