# Generated by Django 5.2.4 on 2025-09-07 12:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("interactions", "0003_initial"),
        ("listings", "0004_listingtype_code_promotion"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Chat",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("active", models.BooleanField(default=True)),
                ("created_date", models.DateTimeField(auto_now_add=True)),
                ("updated_date", models.DateTimeField(auto_now=True)),
                (
                    "listing",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="chats", to="listings.listing"
                    ),
                ),
                ("users", models.ManyToManyField(related_name="chats", to=settings.AUTH_USER_MODEL)),
            ],
            options={
                "unique_together": {("listing",)},
            },
        ),
        migrations.CreateModel(
            name="Cooperation",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("active", models.BooleanField(default=True)),
                ("created_date", models.DateTimeField(auto_now_add=True)),
                ("updated_date", models.DateTimeField(auto_now=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Đang chờ"),
                            ("ACCEPTED", "Đã chấp nhận"),
                            ("REJECTED", "Đã từ chối"),
                            ("SOLD", "BĐS đã bán"),
                            ("CANCELLED", "Đã hủy"),
                        ],
                        default="PENDING",
                        max_length=20,
                        verbose_name="Trạng thái",
                    ),
                ),
                ("rejection_reason", models.TextField(blank=True, null=True, verbose_name="Lý do từ chối")),
                ("cancellation_reason", models.TextField(blank=True, null=True, verbose_name="Lý do hủy")),
                (
                    "agent",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sent_cooperations",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Môi giới yêu cầu",
                    ),
                ),
                (
                    "listing",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cooperations",
                        to="listings.listing",
                        verbose_name="Tin đăng",
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="received_cooperations",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Chủ tin đăng",
                    ),
                ),
            ],
            options={
                "verbose_name": "Hợp tác môi giới",
                "verbose_name_plural": "Các Hợp tác môi giới",
                "unique_together": {("listing", "agent")},
            },
        ),
    ]
