# Generated by Django 5.2.4 on 2025-09-10 14:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("interactions", "0004_chat_cooperation"),
        ("listings", "0007_alter_listingvip_options_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="chat",
            options={"ordering": ["-id"]},
        ),
        migrations.AlterUniqueTogether(
            name="chat",
            unique_together=set(),
        ),
        migrations.AddField(
            model_name="chat",
            name="chat_type",
            field=models.CharField(
                choices=[("PRIVATE", "Private"), ("GROUP", "Group")], default="PRIVATE", max_length=10
            ),
        ),
        migrations.AddField(
            model_name="chat",
            name="name",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="chat",
            name="participants",
            field=models.ManyToManyField(
                help_text="Những người tham gia cuộc trò chuyện.", related_name="chats", to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AlterField(
            model_name="chat",
            name="listing",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="chats",
                to="listings.listing",
            ),
        ),
        migrations.CreateModel(
            name="Message",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("active", models.BooleanField(default=True)),
                ("created_date", models.DateTimeField(auto_now_add=True)),
                ("updated_date", models.DateTimeField(auto_now=True)),
                ("content", models.TextField(blank=True, verbose_name="Nội dung")),
                (
                    "message_type",
                    models.CharField(
                        choices=[
                            ("TEXT", "Tin nhắn văn bản"),
                            ("IMAGE", "Hình ảnh"),
                            ("FILE", "Tệp đính kèm"),
                            ("SYSTEM", "Thông báo hệ thống"),
                            ("LISTING_LINK", "Liên kết tin đăng"),
                            ("APPOINTMENT_REQUEST", "Yêu cầu hẹn gặp"),
                            ("COOPERATION_REQUEST", "Yêu cầu hợp tác"),
                        ],
                        default="TEXT",
                        max_length=25,
                        verbose_name="Loại tin nhắn",
                    ),
                ),
                (
                    "attachment_url",
                    models.URLField(blank=True, max_length=512, null=True, verbose_name="URL tệp đính kèm"),
                ),
                ("metadata", models.JSONField(blank=True, null=True, verbose_name="Dữ liệu bổ sung (Metadata)")),
                (
                    "chat",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="messages",
                        to="interactions.chat",
                        verbose_name="Cuộc trò chuyện",
                    ),
                ),
                (
                    "read_by",
                    models.ManyToManyField(
                        blank=True,
                        related_name="read_messages",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Đã đọc bởi",
                    ),
                ),
                (
                    "sender",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sent_messages",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Người gửi",
                    ),
                ),
            ],
            options={
                "verbose_name": "Tin nhắn",
                "verbose_name_plural": "Các Tin nhắn",
                "ordering": ["created_date"],
            },
        ),
        migrations.RemoveField(
            model_name="chat",
            name="users",
        ),
    ]
