# Generated by Django 5.2.4 on 2025-09-10 16:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        ("interactions", "0005_alter_chat_options_alter_chat_unique_together_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="message",
            name="metadata",
        ),
        migrations.AddField(
            model_name="message",
            name="content_type",
            field=models.ForeignKey(
                blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to="contenttypes.contenttype"
            ),
        ),
        migrations.AddField(
            model_name="message",
            name="object_id",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="message",
            name="message_type",
            field=models.CharField(
                choices=[
                    ("TEXT", "Tin nhắn văn bản"),
                    ("IMAGE", "Hình ảnh"),
                    ("FILE", "Tệp đính kèm"),
                    ("SYSTEM", "Thông báo hệ thống"),
                    ("LISTING_LINK", "Liên kết tin đăng"),
                    ("INTERACTIVE_CARD", "Thẻ tương tác"),
                ],
                default="TEXT",
                max_length=25,
                verbose_name="Loại tin nhắn",
            ),
        ),
    ]
