# Generated by Django 5.2.4 on 2025-09-10 17:40

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("interactions", "0006_remove_message_metadata_message_content_type_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="chat",
            name="last_message_timestamp",
            field=models.DateTimeField(
                db_index=True, default=django.utils.timezone.now, verbose_name="Thời gian tin nhắn cuối"
            ),
        ),
    ]
