# Generated by Django 5.2.4 on 2025-09-17 01:26

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("interactions", "0007_chat_last_message_timestamp"),
    ]

    operations = [
        migrations.AddField(
            model_name="review",
            name="point",
            field=django.contrib.gis.db.models.fields.PointField(
                blank=True, null=True, srid=4326, verbose_name="Vị trí lúc đánh giá"
            ),
        ),
    ]
