# Generated by Django 5.2.4 on 2025-09-17 09:31

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        ("interactions", "0008_review_point"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name="message",
            index=models.Index(fields=["content_type", "object_id"], name="interaction_content_d1edda_idx"),
        ),
    ]
