# Generated by Django 5.2.4 on 2025-09-03 18:07

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Comment",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("active", models.BooleanField(default=True)),
                ("created_date", models.DateTimeField(auto_now_add=True)),
                ("updated_date", models.DateTimeField(auto_now=True)),
                ("content", models.TextField(verbose_name="Nội dung")),
            ],
            options={
                "verbose_name": "Bình luận",
                "verbose_name_plural": "Các Bình luận",
            },
        ),
        migrations.CreateModel(
            name="Post",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("active", models.BooleanField(default=True)),
                ("created_date", models.DateTimeField(auto_now_add=True)),
                ("updated_date", models.DateTimeField(auto_now=True)),
                ("title", models.CharField(max_length=255, verbose_name="Tiêu đề")),
                ("content", ckeditor.fields.RichTextField(verbose_name="Nội dung")),
            ],
            options={
                "verbose_name": "Bài đăng",
                "verbose_name_plural": "Các Bài đăng",
            },
        ),
        migrations.CreateModel(
            name="Reaction",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("active", models.BooleanField(default=True)),
                ("created_date", models.DateTimeField(auto_now_add=True)),
                ("updated_date", models.DateTimeField(auto_now=True)),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("like", "Thích"),
                            ("love", "Yêu thích"),
                            ("haha", "Haha"),
                            ("wow", "Wow"),
                            ("sad", "Buồn"),
                            ("angry", "Giận dữ"),
                        ],
                        max_length=10,
                        verbose_name="Loại cảm xúc",
                    ),
                ),
            ],
            options={
                "verbose_name": "Cảm xúc",
                "verbose_name_plural": "Các Cảm xúc",
            },
        ),
    ]
