# Generated by Django 5.2.4 on 2025-09-03 18:07

import cloudinary.models
import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("password", models.CharField(max_length=128, verbose_name="password")),
                ("last_login", models.DateTimeField(blank=True, null=True, verbose_name="last login")),
                (
                    "is_superuser",
                    models.BooleanField(
                        default=False,
                        help_text="Designates that this user has all permissions without explicitly assigning them.",
                        verbose_name="superuser status",
                    ),
                ),
                (
                    "username",
                    models.CharField(
                        error_messages={"unique": "A user with that username already exists."},
                        help_text="Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.",
                        max_length=150,
                        unique=True,
                        validators=[django.contrib.auth.validators.UnicodeUsernameValidator()],
                        verbose_name="username",
                    ),
                ),
                ("first_name", models.CharField(blank=True, max_length=150, verbose_name="first name")),
                ("last_name", models.CharField(blank=True, max_length=150, verbose_name="last name")),
                (
                    "is_staff",
                    models.BooleanField(
                        default=False,
                        help_text="Designates whether the user can log into this admin site.",
                        verbose_name="staff status",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Designates whether this user should be treated as active. Unselect this instead of deleting accounts.",
                        verbose_name="active",
                    ),
                ),
                ("date_joined", models.DateTimeField(default=django.utils.timezone.now, verbose_name="date joined")),
                (
                    "role",
                    models.CharField(
                        choices=[("admin", "Quản trị viên"), ("user", "Người dùng")],
                        default="user",
                        max_length=10,
                        verbose_name="Vai trò",
                    ),
                ),
                (
                    "phone_number",
                    models.CharField(
                        blank=True, db_index=True, max_length=15, null=True, unique=True, verbose_name="Số điện thoại"
                    ),
                ),
                ("is_phone_verified", models.BooleanField(default=False, verbose_name="Đã xác thực SĐT")),
                ("is_id_card_verified", models.BooleanField(default=False, verbose_name="Đã quét CCCD")),
                (
                    "is_identity_verified",
                    models.BooleanField(default=False, verbose_name="Đã xác thực danh tính (eKYC)"),
                ),
                (
                    "firebase_uid",
                    models.CharField(
                        blank=True, db_index=True, max_length=128, null=True, unique=True, verbose_name="Firebase UID"
                    ),
                ),
                ("email", models.EmailField(blank=True, max_length=254, null=True)),
                (
                    "groups",
                    models.ManyToManyField(
                        blank=True,
                        help_text="The groups this user belongs to. A user will get all permissions granted to each of their groups.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.group",
                        verbose_name="groups",
                    ),
                ),
                (
                    "user_permissions",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Specific permissions for this user.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.permission",
                        verbose_name="user permissions",
                    ),
                ),
            ],
            options={
                "verbose_name": "user",
                "verbose_name_plural": "users",
                "abstract": False,
            },
            managers=[
                ("objects", django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name="UserProfile",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("active", models.BooleanField(default=True)),
                ("created_date", models.DateTimeField(auto_now_add=True)),
                ("updated_date", models.DateTimeField(auto_now=True)),
                (
                    "avatar",
                    cloudinary.models.CloudinaryField(
                        blank=True, max_length=255, null=True, verbose_name="Ảnh đại diện"
                    ),
                ),
                ("date_of_birth", models.DateField(blank=True, null=True, verbose_name="Ngày sinh")),
                (
                    "gender",
                    models.CharField(
                        blank=True,
                        choices=[("male", "Nam"), ("female", "Nữ"), ("other", "Khác")],
                        max_length=10,
                        null=True,
                        verbose_name="Giới tính",
                    ),
                ),
                ("description", models.TextField(blank=True, null=True, verbose_name="Giới thiệu bản thân")),
                (
                    "location",
                    models.CharField(blank=True, max_length=100, null=True, verbose_name="Vị trí (Tỉnh/Thành phố)"),
                ),
                ("nationality", models.CharField(blank=True, max_length=100, null=True, verbose_name="Quốc tịch")),
                ("home_town", models.CharField(blank=True, max_length=255, null=True, verbose_name="Quê quán")),
                (
                    "address",
                    models.CharField(blank=True, max_length=255, null=True, verbose_name="Địa chỉ thường trú"),
                ),
                (
                    "id_card_number",
                    models.CharField(
                        blank=True, db_index=True, max_length=15, null=True, unique=True, verbose_name="Số CCCD/CMND"
                    ),
                ),
                ("rating_score", models.FloatField(default=0.0, verbose_name="Điểm đánh giá trung bình")),
                ("rating_count", models.PositiveIntegerField(default=0, verbose_name="Tổng số lượt đánh giá")),
                ("listing_count", models.PositiveIntegerField(default=0, verbose_name="Tổng số tin đăng hoạt động")),
                ("has_certificate", models.BooleanField(default=False, verbose_name="Có chứng chỉ môi giới")),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="profile",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Người dùng",
                    ),
                ),
            ],
            options={
                "verbose_name": "Hồ sơ Người dùng",
                "verbose_name_plural": "Các Hồ sơ Người dùng",
            },
        ),
        migrations.CreateModel(
            name="Subscription",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("active", models.BooleanField(default=True)),
                ("created_date", models.DateTimeField(auto_now_add=True)),
                ("updated_date", models.DateTimeField(auto_now=True)),
                (
                    "follower",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="following_set",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Người theo dõi",
                    ),
                ),
                (
                    "following",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="follower_set",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Người được theo dõi",
                    ),
                ),
            ],
            options={
                "verbose_name": "Lượt theo dõi",
                "verbose_name_plural": "Các Lượt theo dõi",
                "unique_together": {("follower", "following")},
            },
        ),
    ]
