# Generated by Django 5.2.4 on 2025-10-24 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="listings_sold",
            field=models.PositiveIntegerField(default=0, verbose_name="Số lượng tin đã bán"),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="response_rate",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=5, null=True, verbose_name="Tỷ lệ phản hồi (%)"
            ),
        ),
    ]
