# Generated by Django 5.2.4 on 2025-09-03 18:07

import cloudinary.models
import django.contrib.gis.db.models.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("vi_address", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Direction",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("active", models.BooleanField(default=True)),
                ("created_date", models.DateTimeField(auto_now_add=True)),
                ("updated_date", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(help_text="Tên hướng, ví dụ: Đông, Tây Nam", max_length=50, unique=True)),
                ("element", models.CharField(help_text="Hành tương ứng, ví dụ: Mộc, Kim, Hỏa", max_length=20)),
            ],
            options={
                "verbose_name": "Hướng",
                "verbose_name_plural": "Các Hướng",
            },
        ),
        migrations.CreateModel(
            name="LegalStatus",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("active", models.BooleanField(default=True)),
                ("created_date", models.DateTimeField(auto_now_add=True)),
                ("updated_date", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=100, unique=True, verbose_name="Tên tình trạng pháp lý")),
                ("description", models.TextField(blank=True, null=True, verbose_name="Mô tả/Giải thích")),
            ],
            options={
                "verbose_name": "Tình trạng pháp lý",
                "verbose_name_plural": "Các Tình trạng pháp lý",
            },
        ),
        migrations.CreateModel(
            name="PropertyFeature",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("active", models.BooleanField(default=True)),
                ("created_date", models.DateTimeField(auto_now_add=True)),
                ("updated_date", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=100, unique=True, verbose_name="Tên đặc điểm")),
                (
                    "feature_type",
                    models.CharField(
                        choices=[
                            ("BOOLEAN", "Có / Không"),
                            ("FLOAT", "Số thực"),
                            ("TEXT", "Văn bản"),
                            ("DIRECTION", "Hướng"),
                        ],
                        default="BOOLEAN",
                        max_length=10,
                        verbose_name="Loại giá trị",
                    ),
                ),
            ],
            options={
                "verbose_name": "Đặc điểm Bất động sản",
                "verbose_name_plural": "Các Đặc điểm Bất động sản",
            },
        ),
        migrations.CreateModel(
            name="PropertyMedia",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("active", models.BooleanField(default=True)),
                ("created_date", models.DateTimeField(auto_now_add=True)),
                ("updated_date", models.DateTimeField(auto_now=True)),
                ("url", cloudinary.models.CloudinaryField(max_length=255, verbose_name="media")),
                (
                    "public_id",
                    models.CharField(editable=False, help_text="Public ID từ Cloudinary để xóa file", max_length=255),
                ),
            ],
            options={
                "verbose_name": "Media Bất động sản",
                "verbose_name_plural": "Các Media Bất động sản",
            },
        ),
        migrations.CreateModel(
            name="PropertyType",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("active", models.BooleanField(default=True)),
                ("created_date", models.DateTimeField(auto_now_add=True)),
                ("updated_date", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=100, unique=True)),
                ("code", models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name="Mã code")),
            ],
            options={
                "verbose_name": "Loại Bất động sản",
                "verbose_name_plural": "Các Loại Bất động sản",
            },
        ),
        migrations.CreateModel(
            name="Utility",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("active", models.BooleanField(default=True)),
                ("created_date", models.DateTimeField(auto_now_add=True)),
                ("updated_date", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=100, unique=True)),
            ],
            options={
                "verbose_name": "Tiện ích",
                "verbose_name_plural": "Các Tiện ích",
            },
        ),
        migrations.CreateModel(
            name="Location",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("active", models.BooleanField(default=True)),
                ("created_date", models.DateTimeField(auto_now_add=True)),
                ("updated_date", models.DateTimeField(auto_now=True)),
                ("street", models.CharField(max_length=255, verbose_name="Số nhà, Tên đường")),
                (
                    "point",
                    django.contrib.gis.db.models.fields.PointField(
                        blank=True, null=True, srid=4326, verbose_name="Tọa độ"
                    ),
                ),
                (
                    "ward",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="vi_address.ward",
                        verbose_name="Phường/Xã",
                    ),
                ),
            ],
            options={
                "verbose_name": "Địa điểm",
                "verbose_name_plural": "Các Địa điểm",
            },
        ),
        migrations.CreateModel(
            name="Property",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("active", models.BooleanField(default=True)),
                ("created_date", models.DateTimeField(auto_now_add=True)),
                ("updated_date", models.DateTimeField(auto_now=True)),
                ("area", models.FloatField(verbose_name="Diện tích (m²)")),
                (
                    "direction",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="properties.direction",
                        verbose_name="Hướng",
                    ),
                ),
                (
                    "legal_status",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="properties.legalstatus",
                        verbose_name="Tình trạng pháp lý",
                    ),
                ),
                (
                    "location",
                    models.OneToOneField(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="properties.location",
                        verbose_name="Địa điểm",
                    ),
                ),
            ],
            options={
                "verbose_name": "Bất động sản",
                "verbose_name_plural": "Các Bất động sản",
            },
        ),
    ]
