# Generated by Django 5.2.4 on 2025-09-03 18:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("properties", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="property",
            name="owner",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="properties",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Chủ sở hữu",
            ),
        ),
        migrations.AddField(
            model_name="propertymedia",
            name="property",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="media",
                to="properties.property",
                verbose_name="Bất động sản",
            ),
        ),
        migrations.AddField(
            model_name="propertyfeature",
            name="applicable_property_types",
            field=models.ManyToManyField(
                blank=True, to="properties.propertytype", verbose_name="Áp dụng cho các loại BĐS"
            ),
        ),
        migrations.AddField(
            model_name="property",
            name="property_type",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="properties.propertytype",
                verbose_name="Loại hình BĐS (để thống kê)",
            ),
        ),
        migrations.AddField(
            model_name="property",
            name="utilities",
            field=models.ManyToManyField(blank=True, to="properties.utility", verbose_name="Các tiện ích"),
        ),
    ]
