# Generated by Django 5.2.4 on 2025-09-05 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("properties", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="utility",
            name="code",
            field=models.CharField(
                blank=True,
                help_text="Mã định danh không đổi cho frontend, ví dụ: FULL_INTERIOR",
                max_length=50,
                null=True,
                unique=True,
            ),
        ),
        migrations.AddField(
            model_name="utility",
            name="utility_type",
            field=models.CharField(
                choices=[
                    ("INTERIOR", "Nội thất"),
                    ("AMENITY", "Tiện nghi trong nhà/dự án"),
                    ("NEARBY", "Tiện ích lân cận"),
                    ("OTHER", "Khác"),
                ],
                default="AMENITY",
                max_length=20,
                verbose_name="Loại tiện ích",
            ),
        ),
    ]
