# Generated by Django 5.2.4 on 2025-09-07 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("properties", "0003_utility_code_utility_utility_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="direction",
            name="code",
            field=models.CharField(
                blank=True, help_text="Mã không đổi, ví dụ: EAST, WEST", max_length=20, null=True, unique=True
            ),
        ),
        migrations.AddField(
            model_name="legalstatus",
            name="code",
            field=models.CharField(
                blank=True, help_text="Mã không đổi, ví dụ: SOHONG, HDMB", max_length=50, null=True, unique=True
            ),
        ),
    ]
