# Generated by Django 5.2.4 on 2025-09-07 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("properties", "0005_initial_properties_data"),
    ]

    operations = [
        migrations.AddField(
            model_name="propertyfeature",
            name="code",
            field=models.CharField(
                blank=True,
                help_text="Mã không đổi cho API, ví dụ: NUM_BEDROOMS",
                max_length=50,
                null=True,
                unique=True,
            ),
        ),
    ]
