# Generated by Django 5.2.4 on 2025-09-07 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("properties", "0006_propertyfeature_code"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="property",
            name="utilities",
        ),
        migrations.AddField(
            model_name="propertyfeature",
            name="category",
            field=models.CharField(
                choices=[
                    ("TECHNICAL", "Đặc điểm kỹ thuật"),
                    ("INTERIOR", "Nội thất"),
                    ("AMENITY", "Tiện nghi trong nhà/dự án"),
                    ("NEARBY", "Tiện ích lân cận"),
                    ("OTHER", "Khác"),
                ],
                default="TECHNICAL",
                max_length=20,
                verbose_name="Phân loại (Category)",
            ),
        ),
        migrations.DeleteModel(
            name="Utility",
        ),
    ]
