# Generated by Django 5.2.4 on 2025-09-07 22:54

from django.db import migrations


def populate_features_data(apps, schema_editor):
    PropertyFeature = apps.get_model('properties', 'PropertyFeature')
    PropertyFeature.objects.all().delete()
    print(f"\nDeleted all existing records from properties.PropertyFeature.")

    PropertyFeature.objects.bulk_create([
        # === Đặc điểm kỹ thuật (TECHNICAL) ===
        PropertyFeature(name="Hướng ban công", code="BALCONY_DIRECTION", category="TECHNICAL",
                        feature_type="DIRECTION"),
        PropertyFeature(name="Mặt tiền", code="FACADE_WIDTH", category="TECHNICAL", feature_type="FLOAT"),
        PropertyFeature(name="Độ rộng đường", code="ROAD_WIDTH", category="TECHNICAL", feature_type="FLOAT"),
        PropertyFeature(name="Số tầng", code="NUM_FLOORS", category="TECHNICAL", feature_type="FLOAT"),
        PropertyFeature(name="Số phòng ngủ", code="NUM_BEDROOMS", category="TECHNICAL", feature_type="FLOAT"),
        PropertyFeature(name="Số phòng tắm", code="NUM_BATHROOMS", category="TECHNICAL", feature_type="FLOAT"),

        # === Nội thất (INTERIOR) ===
        PropertyFeature(name="Tình trạng nội thất", code="INTERIOR_STATUS", category="INTERIOR", feature_type="TEXT"),
        PropertyFeature(name="Điều hòa", code="HAS_AC", category="INTERIOR", feature_type="BOOLEAN"),
        PropertyFeature(name="Nóng lạnh", code="HAS_HEATER", category="INTERIOR", feature_type="BOOLEAN"),

        # === Tiện nghi (AMENITY) ===
        PropertyFeature(name="Có chỗ đỗ ô tô", code="HAS_CAR_PARKING", category="AMENITY", feature_type="BOOLEAN"),
        PropertyFeature(name="Có sân vườn", code="HAS_GARDEN", category="AMENITY", feature_type="BOOLEAN"),
        PropertyFeature(name="Có hồ bơi", code="HAS_POOL", category="AMENITY", feature_type="BOOLEAN"),
        PropertyFeature(name="Phòng gym", code="HAS_GYM", category="AMENITY", feature_type="BOOLEAN"),

        # === Tiện ích lân cận (NEARBY) ===
        PropertyFeature(name="Gần trường học", code="NEAR_SCHOOL", category="NEARBY", feature_type="BOOLEAN"),
        PropertyFeature(name="Gần bệnh viện", code="NEAR_HOSPITAL", category="NEARBY", feature_type="BOOLEAN"),
    ])
    print("Created all PropertyFeature records (technical and utilities).")

def unpopulate_features_data(apps, schema_editor):
    """
    Hàm rollback, xóa tất cả các bản ghi PropertyFeature đã tạo.
    """
    PropertyFeature = apps.get_model('properties', 'PropertyFeature')
    PropertyFeature.objects.all().delete()
    print(f"\nDeleted all records from properties.PropertyFeature during rollback.")

class Migration(migrations.Migration):

    dependencies = [
        ("properties", "0007_remove_property_utilities_propertyfeature_category_and_more"),
    ]

    operations = [
        migrations.RunPython(populate_features_data, unpopulate_features_data)
    ]
