# Generated by Django 5.2.4 on 2025-09-17 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("properties", "0009_convert_details_to_features"),
    ]

    operations = [
        migrations.AlterField(
            model_name="property",
            name="area",
            field=models.FloatField(db_index=True, verbose_name="Diện tích (m²)"),
        ),
    ]
