# Generated by Django 5.2.4 on 2025-10-27 03:12

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("properties", "0010_alter_property_area"),
    ]

    operations = [
        migrations.AddField(
            model_name="propertymedia",
            name="media_type",
            field=models.CharField(
                choices=[
                    ("IMAGE", "Hình ảnh"),
                    ("VIDEO", "Video (Tải lên)"),
                    ("EXTERNAL_VIDEO", "Video (Liên kết ngoài)"),
                ],
                default="IMAGE",
                max_length=20,
                verbose_name="Loại media",
            ),
        ),
        migrations.AddField(
            model_name="propertymedia",
            name="source_url",
            field=models.URLField(
                blank=True, max_length=512, null=True, verbose_name="URL gốc (Youtube, Tiktok, ...)"
            ),
        ),
        migrations.AlterField(
            model_name="propertymedia",
            name="public_id",
            field=models.CharField(
                blank=True, editable=False, help_text="Public ID từ Cloudinary để xóa file", max_length=255, null=True
            ),
        ),
        migrations.AlterField(
            model_name="propertymedia",
            name="url",
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name="media"),
        ),
    ]
