# Generated by Django 5.2.4 on 2025-09-04 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="SiteStatistic",
            fields=[
                (
                    "key",
                    models.CharField(
                        help_text="Khóa định danh cho số liệu, ví dụ: 'total_active_listings'",
                        max_length=100,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("value", models.PositiveIntegerField(default=0, help_text="Giá trị của số liệu")),
                ("last_updated", models.DateTimeField(auto_now=True, help_text="Lần cuối cập nhật")),
            ],
            options={
                "verbose_name": "Thống kê Trang",
                "verbose_name_plural": "Các Thống kê Trang",
            },
        ),
    ]
