# Generated by Django 5.2.4 on 2025-09-17 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("common", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="GeoGridStatistic",
            fields=[
                (
                    "grid_cell_id",
                    models.CharField(max_length=100, primary_key=True, serialize=False, verbose_name="Grid Cell ID"),
                ),
                ("center_lat", models.FloatField(null=True)),
                ("center_lng", models.FloatField(null=True)),
                (
                    "avg_rent_price",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=19,
                        null=True,
                        verbose_name="Giá thuê trung bình (VND/tháng)",
                    ),
                ),
                ("rent_listing_count", models.PositiveIntegerField(default=0, verbose_name="Số lượng tin cho thuê")),
                (
                    "avg_sell_price_per_m2",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=19, null=True, verbose_name="Giá bán trung bình (/m²)"
                    ),
                ),
                ("sell_listing_count", models.PositiveIntegerField(default=0, verbose_name="Số lượng tin mua bán")),
                ("last_updated", models.DateTimeField(auto_now=True, verbose_name="Lần cuối cập nhật")),
            ],
            options={
                "verbose_name": "Thống kê giá theo Lưới",
                "verbose_name_plural": "Các Thống kê giá theo Lưới",
            },
        ),
    ]
