# Generated by Django 5.2.4 on 2025-09-19 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("common", "0002_geogridstatistic"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="geogridstatistic",
            name="avg_rent_price",
        ),
        migrations.RemoveField(
            model_name="geogridstatistic",
            name="avg_sell_price_per_m2",
        ),
        migrations.RemoveField(
            model_name="geogridstatistic",
            name="rent_listing_count",
        ),
        migrations.RemoveField(
            model_name="geogridstatistic",
            name="sell_listing_count",
        ),
        migrations.AddField(
            model_name="geogridstatistic",
            name="stats_by_category",
            field=models.JSONField(blank=True, default=dict, verbose_name="Thống kê theo từng Danh mục"),
        ),
    ]
