# Generated by Django 5.2.4 on 2025-09-03 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Protest",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("active", models.BooleanField(default=True)),
                ("created_date", models.DateTimeField(auto_now_add=True)),
                ("updated_date", models.DateTimeField(auto_now=True)),
                ("reason", models.TextField(verbose_name="Lý do kháng nghị")),
                ("resolution_note", models.TextField(blank=True, null=True, verbose_name="Ghi chú xử lý")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("IN_PROGRESS", "Đang xem xét"),
                            ("RESOLVED", "Đã giải quyết"),
                            ("REJECTED", "Từ chối"),
                        ],
                        default="IN_PROGRESS",
                        max_length=20,
                        verbose_name="Trạng thái",
                    ),
                ),
            ],
            options={
                "verbose_name": "Kháng nghị",
                "verbose_name_plural": "Các Kháng nghị",
            },
        ),
        migrations.CreateModel(
            name="Report",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("active", models.BooleanField(default=True)),
                ("created_date", models.DateTimeField(auto_now_add=True)),
                ("updated_date", models.DateTimeField(auto_now=True)),
                ("description", models.TextField(verbose_name="Mô tả")),
                (
                    "status",
                    models.CharField(
                        choices=[("PENDING", "Chờ xử lý"), ("RESOLVED", "Đã giải quyết"), ("REJECTED", "Từ chối")],
                        default="PENDING",
                        max_length=20,
                        verbose_name="Trạng thái",
                    ),
                ),
                ("reported_item_id", models.PositiveIntegerField(verbose_name="ID đối tượng bị báo cáo")),
                (
                    "reported_item_type",
                    models.CharField(
                        choices=[
                            ("listing", "Tin đăng"),
                            ("user", "Người dùng"),
                            ("post", "Bài đăng"),
                            ("comment", "Bình luận"),
                        ],
                        max_length=20,
                        verbose_name="Loại đối tượng bị báo cáo",
                    ),
                ),
            ],
            options={
                "verbose_name": "Báo cáo",
                "verbose_name_plural": "Các Báo cáo",
            },
        ),
    ]
