# Generated by Django 5.2.4 on 2025-09-03 18:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("listings", "0003_initial"),
        ("moderation", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="protest",
            name="admin",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="handled_protests",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Admin xử lý",
            ),
        ),
        migrations.AddField(
            model_name="protest",
            name="listing",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="protests",
                to="listings.listing",
                verbose_name="Tin đăng",
            ),
        ),
        migrations.AddField(
            model_name="protest",
            name="protester",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="protests",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Người kháng nghị",
            ),
        ),
        migrations.AddField(
            model_name="report",
            name="reporter",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="sent_reports",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Người báo cáo",
            ),
        ),
    ]
