# Generated by Django 5.2.4 on 2025-09-15 17:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        ("moderation", "0002_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name="protest",
            name="admin",
        ),
        migrations.RemoveField(
            model_name="protest",
            name="listing",
        ),
        migrations.AddField(
            model_name="protest",
            name="admin_reviewer",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="reviewed_protests",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Admin xem xét kháng nghị",
            ),
        ),
        migrations.AlterField(
            model_name="protest",
            name="resolution_note",
            field=models.TextField(blank=True, null=True, verbose_name="Ghi chú xử lý kháng nghị"),
        ),
        migrations.AlterField(
            model_name="report",
            name="reported_item_id",
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name="report",
            name="reported_item_type",
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="contenttypes.contenttype"),
        ),
        migrations.CreateModel(
            name="ModerationAction",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("active", models.BooleanField(default=True)),
                ("created_date", models.DateTimeField(auto_now_add=True)),
                ("updated_date", models.DateTimeField(auto_now=True)),
                (
                    "action_type",
                    models.CharField(
                        choices=[
                            ("TAKE_DOWN", "Gỡ nội dung"),
                            ("RESTORE", "Khôi phục nội dung"),
                            ("WARN", "Cảnh cáo người dùng"),
                            ("BAN", "Khóa tài khoản người dùng"),
                        ],
                        max_length=20,
                    ),
                ),
                ("reason", models.TextField(help_text="Ghi chú của admin về lý do thực hiện hành động này.")),
                ("target_object_id", models.PositiveIntegerField()),
                (
                    "moderator",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="moderation_actions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "report",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="actions",
                        to="moderation.report",
                    ),
                ),
                (
                    "target_content_type",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="contenttypes.contenttype"),
                ),
            ],
            options={
                "verbose_name": "Hành động Xử lý",
                "verbose_name_plural": "Các Hành động Xử lý",
            },
        ),
        migrations.AddField(
            model_name="protest",
            name="action",
            field=models.OneToOneField(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="protest",
                to="moderation.moderationaction",
                verbose_name="Hành động bị kháng nghị",
            ),
            preserve_default=False,
        ),
    ]
