# Generated by Django 5.2.4 on 2025-09-17 09:31

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        ("moderation", "0003_remove_protest_admin_remove_protest_listing_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name="report",
            index=models.Index(
                fields=["reported_item_type", "reported_item_id"], name="moderation__reporte_f255b3_idx"
            ),
        ),
    ]
